package tablas;

import javax.persistence.*;

// Generated 04-jul-2017 8:42:29 by Hibernate Tools 5.2.3.Final

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="Person")

public class Person implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1058296340393155428L;

	@Id
	@Column(name="ID")
	private int id;
	
	@Column(name="NAME")
	private String name;
	
	@Column(name="ADDRESS")
	private String address;
	
	@Column(name="AGE")
	private Integer age;

	public Person() {
	}

	public Person(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Person(int id, String name, String address, Integer age) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.age = age;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Override
	public String toString() {
		return id + "\t " + name + "\t\t " + address + "\t\t " + age;
	}


	
	

}
